main/urls.py
from django.urls import path

from main.views import MainView, ContactView

urlpatterns = [
    path('', MainView.as_view(), name='main'),
    path('contact/', ContactView.as_view(), name='contacts'),


]

orders/urls.py
from django.urls import path, re_path

from orders.views import OrdersView, CartView, CartActionView

urlpatterns = [
    path('orders/', OrdersView.as_view(), name='orders'),
    path('cart/', CartView.as_view(), name='cart'),
    re_path(r'cart/(?P<action>add|remove|clear|pay)/',
            CartActionView.as_view(),
            name='cart_action'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from products.urls import urlpatterns as products_urlpatterns
from orders.urls import urlpatterns as orders_urlpatterns
from feedbacks.urls import urlpatterns as feedbacks_urlpatterns
from accounts.urls import urlpatterns as accounts_urlpatterns
from main.urls import urlpatterns as main_urlpatterns
from django.conf import settings
from favourites.urls import urlpatterns as favourites_urlpatterns
# from currencies.urls import urlpatterns as currencies_urlpatterns
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import set_language


urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include(products_urlpatterns)),
    path('orders/', include(orders_urlpatterns)),
    path('feedbacks/', include(feedbacks_urlpatterns)),
    path('accounts/', include(accounts_urlpatterns)),
    path('', include(main_urlpatterns)),
    path('favourites/', include(favourites_urlpatterns)),

    # path('currencies/', include(currencies_urlpatterns)),
    path('set-language/', set_language, name='set_language'),
]

urlpatterns = i18n_patterns(*urlpatterns)


if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        path('rosetta/', include('rosetta.urls'))
    ]

if settings.ENABLE_SILK:
    urlpatterns += [path('silk/', include('silk.urls', namespace='silk')),
                    path("__debug__/", include("debug_toolbar.urls"))
                    ]

orders/models.py
import decimal

from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import Sum, F
from django.utils import timezone

from project.constants import MAX_DIGITS, DECIMAL_PLACES
from project.mixins.models import PKMixin
from project.model_choices import DiscountTypes

from django_lifecycle import LifecycleModelMixin, AFTER_SAVE, hook, \
    AFTER_UPDATE

User = get_user_model()


class Discount(PKMixin):
    amount = models.DecimalField(
        max_digits=MAX_DIGITS,
        decimal_places=DECIMAL_PLACES,
        default=0
    )
    code = models.CharField(
        max_length=32,
        unique=True
    )
    is_active = models.BooleanField(
        default=True
    )
    discount_type = models.PositiveSmallIntegerField(
        choices=DiscountTypes.choices,
        default=DiscountTypes.VALUE
    )
    discount_value = models.DecimalField(
        max_digits=MAX_DIGITS,
        decimal_places=DECIMAL_PLACES,
        default=0
    )
    valid_until = models.DateTimeField(
        null=True,
        blank=True
    )

    def __str__(self):
        return f"{self.discount_value} | {self.code} | " \
               f"{DiscountTypes(self.discount_type).label}"

    # проверяем на то чтобы акция была актуальной
    @property
    def is_valid(self):
        is_valid = self.is_active
        if self.valid_until:
            is_valid &= (timezone.now() <= self.valid_until)
        return is_valid


class Order(LifecycleModelMixin, PKMixin):
    total_amount = models.DecimalField(
        max_digits=MAX_DIGITS,
        decimal_places=DECIMAL_PLACES,
        default=0
    )
    user = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    discount = models.ForeignKey(
        Discount,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    is_active = models.BooleanField(default=True)
    is_paid = models.BooleanField(default=False)
    order_number = models.PositiveSmallIntegerField(default=1)

    # UniqueConstraint, который гарантирует, что у
    # каждого пользователя (user) может быть только
    # один активный заказ.
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user'],
                                    condition=models.Q(is_active=True),
                                    name='unique_is_active')
        ]

    def __str__(self):
        return f"User: {self.user}  " \
               f"Total amount: {self.total_amount}  " \
               f"Discount: ({ self.discount })"

    # Это свойство (property), которое определяет,
    # является ли заказ текущим. Заказ считается
    # текущим, если он активен (is_active=True)
    # и не оплачен (is_paid=False).
    @property
    def is_current_order(self):
        return self.is_active and not self.is_paid

    def get_total_amount(self):
        total_amount = self.order_items.aggregate(
            total_amount=Sum(F('price') * F('quantity'))
        )['total_amount'] or 0
        total_amount = decimal.Decimal(total_amount)
        if self.discount and self.discount.is_valid:
            total_amount = (
                total_amount - self.discount.amount
                if self.discount.discount_type == DiscountTypes.VALUE else
                total_amount - (total_amount / 100 * self.discount.amount)
            ).quantize(decimal.Decimal('.01'))

        return total_amount

    #  Это метод-хук (hook), который вызывается после
    #  обновления заказа.
    #  Он обновляет поле total_amount вызовом метода
    #  get_total_amount()
    #  и сохраняет изменения, пропуская хуки, чтобы
    #  избежать рекурсивных вызовов.

    @hook(AFTER_UPDATE, when='discount', has_changed=True)
    def set_total_amount(self):
        self.total_amount = self.get_total_amount()
        self.save(update_fields=('total_amount',), skip_hooks=True)


class OrderItem(LifecycleModelMixin, PKMixin):
    is_active = models.BooleanField(default=True)
    order = models.ForeignKey(
        Order,
        on_delete=models.PROTECT,
        related_name='order_items'
    )
    product = models.ForeignKey(
        'products.Product',
        on_delete=models.PROTECT,
        related_name='order_items',
    )
    quantity = models.PositiveSmallIntegerField(default=1)
    price = models.DecimalField(
        max_digits=MAX_DIGITS,
        decimal_places=DECIMAL_PLACES
    )

    # Это внутренний класс Meta, который
    # определяет уникальность пары полей order и product.
    # Это гарантирует, что каждый товар в заказе является уникальным.
    class Meta:
        unique_together = ('order', 'product')

    # Это свойство (property), которое вычисляет
    # подытог для данного товара. Оно умножает
    # цену товара на количество и возвращает результат.
    @property
    def sub_total(self):
        return self.product.price * self.quantity

    # Это метод-хук (hook), который вызывается после
    # сохранения товара в заказе.
    # Он обновляет общую сумму заказа, вызывая метод get_total_amount()
    # у связанного объекта order и сохраняет изменения, пропуская хуки,
    # чтобы избежать рекурсивных вызовов.
    @hook(AFTER_SAVE)
    def set_order_total_amount(self):
        self.order.total_amount = self.order.get_total_amount()
        self.order.save(update_fields=('total_amount',), skip_hooks=True)

orders/views.py
from django.shortcuts import render  # , redirect
from django.views import View

from django.contrib.auth.decorators import login_required
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import FormView, RedirectView

from orders.mixins import GetCurrentOrderMixin
from orders.forms import CartForm, CartActionForm
from django.http import HttpResponseRedirect
from django.utils.translation import gettext_lazy as _
from django.contrib import messages


# rewritte in OOP
# def orders(request, *args, **kwargs):
#     # breakpoint()
#     return render(request, 'orders/index.html')


class OrdersView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'orders/index.html')

# Не получилось самому взял как у учителя
# class CartView(View):
#     form_class = CartForm
#     template_name = 'orders/cart.html'
#     success_url = None
#     def get(self, request):
#         # Логика получения содержимого корзины
#         # ...
#         # Заменить на свою логику получения товаров из корзины
#         # cart_items = []
#         cart_items = orders.order_items.all()
#           # Заменить на свою логику получения общей суммы корзины
#         cart_total = 0
#
#         return render(request, 'orders/cart.html', {
#             'cart_items': cart_items,
#             'cart_total': cart_total,
#         })
#
#
# class AddToCartView(View):
#     def post(self, request, product_id):
#         # Логика добавления товара в корзину
#         # ...
#
#         return redirect('cart')
#
#
# class RemoveFromCartView(View):
#     def post(self, request, cart_item_id):
#         # Логика удаления товара из корзины
#         # ...
#
#         return redirect('cart')
#
#
# class ApplyDiscountView(View):
#     def post(self, request):
#         # Логика применения скидки к корзине
#         # ...
#
#         return redirect('cart')
#
#
# class CheckoutView(View):
#     def post(self, request):
#         # Логика оформления заказа
#         # ...
#
#         return redirect('cart')


# представление, отображающее корзину и обрабатывающее форму
class CartView(GetCurrentOrderMixin, FormView):
    #: указывает класс формы, используемой представлением,
    # в данном случае - CartForm.
    form_class = CartForm
    template_name = 'orders/cart.html'
    # : указывает URL, на который будет перенаправлен
    # метод-хук, применяющий декоратор login_required
    # для требования аутентификации пользователя
    # перед доступом к представлению.

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    #  метод, возвращающий URL для перенаправления
    #  пользователя после успешной обработки формы.
    def get_success_url(self):
        return reverse('cart')

    #  метод, возвращающий контекст данных для
    #  передачи в шаблон.
    #  Он добавляет объект order и связанные с ним
    #  объекты order_items в контекст.
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        order = self.get_object()
        # breakpoint()
        # total_amount = order.get_total_amount() if order else 0
        cart_items_count = order.order_items.count() if order else 0
        context.update({
            'order': order,
            # 'order_items': order.order_items.all()
            'order_items': order.order_items.select_related('product').all(),
            'cart_items_count': cart_items_count,
            # 'total_amount': total_amount
        })
        return context

    # метод, возвращающий аргументы для создания
    # экземпляра формы. В данном случае,
    # он добавляет instance (текущий заказ) в аргументы формы.
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'instance': self.get_object()})
        return kwargs

    # метод, вызываемый при успешной валидации формы.
    # Он сохраняет данные формы с помощью метода save() формы.
    def form_valid(self, form):
        # breakpoint()
        form.save()
        return super().form_valid(form)


#  представление, обрабатывающее действия в корзине,
#  такие как добавление товара,
#  удаление товара, очистка корзины и оплата.
#  Оно также наследуется от GetCurrentOrderMixin и RedirectView
class CartActionView(GetCurrentOrderMixin, RedirectView):
    url = reverse_lazy('products')

    #  метод-хук, применяющий декоратор login_required
    #  для требования аутентификации пользователя
    #  перед доступом к представлению
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    #  метод, обрабатывающий POST-запросы.
    #  Он создает экземпляр формы CartActionForm с переданными данными POST
    #  и текущим заказом, а затем вызывает метод action() формы,
    #  передавая действие (action) из параметров запроса.
    def post(self, request, *args, **kwargs):
        form = CartActionForm(request.POST, instance=self.get_object())
        # Если форма валидна, то выполняется
        # соответствующее действие (add, pay, remove, clear).
        if form.is_valid():
            action = self.kwargs['action']
            if action == 'remove':
                form.action(kwargs.get('action'))
                return HttpResponseRedirect(reverse('cart'))
        form.action(kwargs.get('action'))
        messages.success(
            self.request, _('Added')
        )
        return self.get(request, *args, **kwargs)

templates/orders/cart.html
{% extends 'base.html' %}
{% load i18n %}
<title>{% block title %}
    {% translate 'Your cart' %}
{% endblock title %}</title>

{% block content %}
    <div class="col-12 my-3 my-lg-5">
        {% if order_items %}
            <h2 class="position-relative start-50">Your cart</h2>
            <form method="post">
                {% csrf_token %}
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Product</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Prices</th>
                        <th scope="col">Subtotal</th>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in order_items %}
                        <tr>
                            <th scope="row"
                                class="1">{{ forloop.counter }}</th>
                            <td>
                                {{ item.product.name }}
                                <input type="hidden"
                                       id="item_id_{{ forloop.counter }}"
                                       name="item_{{ forloop.counter }}"
                                       value="{{ item.id }}">
                            </td>
                            <td class="col-1">
                                <input class="form-control" type="number"
                                       id="quantity_id_{{ forloop.counter }}"
                                       value="{{ item.quantity }}"
                                       name="quantity_{{ forloop.counter }}"
                                       min="1">
                            </td>
                            <td class="col-1">
                                {{ item.product.price }}
                            </td>
                            <td class="col-1">
                                {{ item.sub_total }}
                            </td>
                            <td class="col-1">
                                <input type="hidden" name="order_item_id"
                                       value="{{ item.id }}">
                                <button type="submit" class="btn follow" name="remove_item"
                                        formaction="{% url 'cart_action' 'remove' %}">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                         fill="red"
                                         class="bi bi-trash" viewBox="0 0 16 16">
                                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z"/>
                                        <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z"/>
                                    </svg>
                                </button>
                            </td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>Total :</td>

                        <td>{{ order.total_amount }}</td>
                    </tr>
                    </tbody>
                    <tr>
                        <td></td>
                        {#                        <td></td>#}
                        {% if not order.discount %}
                            <td><label for="id_discount">
                                Have a discount code? Please enter here.
                            </label></td>
                            <td><input class="form-control" id="id_discount"
                                       type="text"
                                       name="discount"></td>

                        {% else %}
                            <td colspan="2">
                               You already applied discount.
                            </td>
                        {% endif %}
                        <td><input type="submit" class="btn btn-primary"
                                   name="recalculate" value="Recalculate"></td>
                    </tr>
                </table>
            </form>
            <form method="post" action="{% url 'cart_action' 'pay' %}">
                {% csrf_token %}
                <input type="submit" value="Pay order"
                       class="btn btn-warning w-100">
            </form>

            <form method="post" action="{% url 'cart_action' 'clear' %}">
                {% csrf_token %}
                <input type="submit" value="Clear this order"
                       class="col-2 btn btn-info position-relative start-50 mt-5">
            </form>

            {% if form.errors %}
                <div class="mb-2">
                    <ul>
                        {% for error in form.errors %}
                            <li class="text-danger small">{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
            {% if form.non_field_errors %}
                <div class="mb-2">
                    <ul>
                        {% for error in form.non_field_errors %}
                            <li class="text-danger small">{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        {% else %}
            <h2>Your cart is empty.</h2>
            <p><a href="{% url 'products' %}">Return to products</a></p>
        {% endif %}
    </div>
{% endblock content %}

templates/orders/index.html
{% extends 'base.html' %}

{% block content %}
<div class="py-3" >
    <h2>Your orders</h2>
    <form method="GET">
        {% csrf_token %}


    </form>
</div>

{% endblock content%}